### ISSUE TITLE
SSH connection drops with image build locally

### ISSUE THREAD

**Issue by KunalMGupta** [works-on-my-machine/pytorch-code-server#2]
Hi, 

Thanks again for releasing the Dockerfile for code-server and PyTorch. I was trying to customize it for my own use case however I stumbled upon a problem. Before I begin, I must say that using your prebuilt image `ghcr.io/works-on-my-machine/pytorch-code-server:1.9.1` works perfectly fine. It's just that when I build the docker file in this repo on my end and launch it, the connection keeps on dropping.
![Screen Shot 2022-01-29 at 6 17 02 PM](https://user-images.githubusercontent.com/46138021/151680665-47dde0ac-9037-407e-9212-9b6e40362dcb.png)

![Screen Shot 2022-01-29 at 6 17 43 PM](https://user-images.githubusercontent.com/46138021/151680679-1b78afbe-1236-4bbb-a56a-59b8237085be.png)

I am running on the image on a Linux machine which otherwise never had any problem with ssh. I tested both by port-forwarding it to my local machine (Mac OS, Chrome) as well as accessing it on the very same machine. In both cases, I am getting the same problem. Do you know what can be the problem? Can you share the original docker file you used to build original image?

Thanks!

**Comment by ghokun** [comment]
Hi,

The image is built by github workflow and the dockerfile is already in the root folder of this repo.

Similar issues are seen here:
https://github.com/microsoft/vscode-remote-release/issues/2192

Can it be related to an extension you have installed?

**Comment by KunalMGupta** [comment]
I think the issue is related to the latest release v4.0.2 as mentioned here: https://github.com/coder/code-server/issues/4693

I was able to resolve this problem by downgrading to version 3.12.0. I simply set the coder-server version in the docker file to 3.12.0 and it started working normally. 

Thanks again for the prompt response!
